let handler = m => m

handler.before = function (m) {
    let user = global.db.data.users[m.sender]
    let role = (user.level <= 2) ? 'مواطن 👦🏻'
      : ((user.level >= 2) && (user.level <= 4)) ? 'شونين 👦🏻🗡️'
      : ((user.level >= 4) && (user.level <= 6)) ? 'شينوبي 🗡️'
      : ((user.level >= 6) && (user.level <= 8)) ? 'جندي بحرية 👮🏼‍♀️'
      : ((user.level >= 8) && (user.level <= 10)) ? 'صائد قراصنة 💀'
      : ((user.level >= 10) && (user.level <= 12)) ? 'قبطان 👨🏻‍✈️'
      : ((user.level >= 12) && (user.level <= 14)) ? 'شونين⚔️'
      : ((user.level >= 14) && (user.level <= 16)) ? 'ساحر🧙‍♂️'
      : ((user.level >= 16) && (user.level <= 18)) ? 'الجاسوس🕵️‍♂️'
      : ((user.level >= 18) && (user.level <= 20)) ? 'معالج⛑️'
      : ((user.level >= 20) && (user.level <= 22)) ? 'كاغي 🎗'
      : ((user.level >= 22) && (user.level <= 24)) ? 'قائد اسطول ☠️'
      : ((user.level >= 24) && (user.level <= 26)) ? 'الفارس الأسود 🖤'
      : ((user.level >= 26) && (user.level <= 28)) ? 'ساموراي 🗡️'
      : ((user.level >= 28) && (user.level <= 30)) ? 'قاتل شياطين 👌🏻'
      : ((user.level >= 30) && (user.level <= 32)) ? 'وريث هاشيرا 🔥'
      : ((user.level >= 32) && (user.level <= 34)) ? 'هاشيرا ⚕️'
      : ((user.level >= 34) && (user.level <= 36)) ? 'قمر ادنى 👿'
      : ((user.level >= 36) && (user.level <= 38)) ? 'قمر أعلى 👹'
      : ((user.level >= 38) && (user.level <= 40)) ? 'الصيادن 🏹'
      : ((user.level >= 40) && (user.level <= 42)) ? 'مساعد حاكم الدمار 🐱'
      : ((user.level >= 42) && (user.level <= 44)) ? 'حاكم الدمار👺'
      : ((user.level >= 44) && (user.level <= 46)) ? 'اسبادا 🔮'
      : ((user.level >= 46) && (user.level <= 48)) ? 'تارتاروس 👹'
      : ((user.level >= 48) && (user.level <= 50)) ? 'امبرطور 👑'
      : ((user.level >= 50) && (user.level <= 52)) ? 'سايان 🔥'
      : ((user.level >= 52) && (user.level <= 54)) ? 'شينيغامي 💀'
      : ((user.level >= 54) && (user.level <= 56)) ? 'اوتشيها🔥'
      : ((user.level >= 56) && (user.level <= 58)) ? 'هوكاجي💥'
      : ((user.level >= 58) && (user.level <= 60)) ? 'سوبر مان🦹‍♂️'
      : ((user.level >= 60) && (user.level <= 62)) ? 'بطل خارق⚡'
      : ((user.level >= 62) && (user.level <= 64)) ? 'الافاتار🌊'
      : ((user.level >= 64) && (user.level <= 66)) ? 'تنين 🐉'
      : ((user.level >= 66) && (user.level <= 68)) ? 'ملك التنانين 👑'
      : ((user.level >= 68) && (user.level <= 70)) ? 'تشيبوكاي 🪝'      
      : ((user.level >= 70) && (user.level <= 72)) ? 'نائب يونكو 💂🏼'
      : ((user.level >= 72) && (user.level <= 74)) ? 'يونكو 🧛🏻'
      : ((user.level >= 74) && (user.level <= 76)) ? 'عملاق الموسس🐒'
      : ((user.level >= 76) && (user.level <= 78)) ? 'نائب ملك قراصنة🏴‍☠️'
      : ((user.level >= 78) && (user.level <= 80)) ? 'ملك قراصنة👒'
      : ((user.level >= 80) && (user.level <= 82)) ? 'منقطع النظير 🔱'
      : ((user.level >= 82) && (user.level <= 84)) ? 'الأسطورة'
      : ((user.level >= 84) && (user.level <= 86)) ? 'القوت 🐐'
      : ((user.level >= 86) && (user.level <= 90)) ? 'العم'
      : 'العم آرثر'

    user.role = role
    return true
}

export default handler
